# Generated by Django 2.1.6 on 2019-02-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(max_length=30)),
                ('full_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('web_page', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
