# Generated by Django 2.1.6 on 2019-02-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20190215_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='web_page',
            field=models.CharField(max_length=300),
        ),
    ]
