# Generated by Django 2.1.6 on 2019-04-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_values'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_file', models.FileField(blank=True, null=True, upload_to='')),
                ('project_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProcessProductTracking')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
