# Generated by Django 2.1.6 on 2019-04-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190319_1736'),
        ('supervisor', '0002_auto_20190227_1816'),
        ('project', '0003_auto_20190319_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_title', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.Supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('eval_id', models.AutoField(primary_key=True, serialize=False)),
                ('plagiarism_documentation', models.IntegerField(blank=True, null=True)),
                ('plagiarism_source_code', models.IntegerField(blank=True, null=True)),
                ('supervisor_mark', models.IntegerField(blank=True, null=True)),
                ('internal_01_mark', models.IntegerField(blank=True, null=True)),
                ('internal_02_mark', models.IntegerField(blank=True, null=True)),
                ('external_mark', models.IntegerField(blank=True, null=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectPrimaryInfo')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessProductTracking',
            fields=[
                ('ppt_id', models.AutoField(primary_key=True, serialize=False)),
                ('srs', models.CharField(blank=True, max_length=200, null=True)),
                ('spmp', models.CharField(blank=True, max_length=200, null=True)),
                ('release_plan', models.CharField(blank=True, max_length=200, null=True)),
                ('iteration_plan', models.CharField(blank=True, max_length=200, null=True)),
                ('system_architecture_design', models.CharField(blank=True, max_length=200, null=True)),
                ('coding_standard', models.CharField(blank=True, max_length=200, null=True)),
                ('test_plan', models.CharField(blank=True, max_length=200, null=True)),
                ('test_case_specification', models.CharField(blank=True, max_length=200, null=True)),
                ('user_guide', models.CharField(blank=True, max_length=200, null=True)),
                ('system_video_documentation', models.CharField(blank=True, max_length=200, null=True)),
                ('video_demonstration', models.CharField(blank=True, max_length=200, null=True)),
                ('source_code_link', models.CharField(blank=True, max_length=200, null=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectPrimaryInfo')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Supervised',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Category')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectPrimaryInfo')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.Supervisor')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='ppt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProcessProductTracking'),
        ),
        migrations.AddField(
            model_name='comment',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
