# Generated by Django 2.1.6 on 2019-04-07 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_documenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='file_tracking_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.DocumentType'),
        ),
    ]
