# Generated by Django 2.1.6 on 2019-04-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_productfile_file_tracking_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processproducttracking',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='processproducttracking',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='ppt_field',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='ppt_id',
        ),
        migrations.RemoveField(
            model_name='productfile',
            name='project_tracking',
        ),
        migrations.AddField(
            model_name='comment',
            name='process_product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.DocumentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='process_product_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ProcessProductTracking',
        ),
    ]
