# Generated by Django 2.1.6 on 2019-04-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_values'),
        ('project', '0008_remove_supervised_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervised',
            name='p_id',
        ),
        migrations.AddField(
            model_name='projectprimaryinfo',
            name='s_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AlterField(
            model_name='supervised',
            name='s_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AlterField(
            model_name='supervised',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supervised',
            name='supervisor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervisor.Supervisor'),
        ),
    ]
