# Generated by Django 2.1.6 on 2019-04-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='marks',
            new_name='marks_allowed',
        ),
        migrations.AddField(
            model_name='task',
            name='marks_allocated',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
