# Generated by Django 2.1.6 on 2019-04-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190319_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
