# Generated by Django 2.1.6 on 2019-02-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='web_page',
            field=models.URLField(),
        ),
    ]
